name: Build Docker Image

on:
  push:
    branches:
      - main

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  DOCKER_IMAGE_REPOSITORY: osmolabs/droid

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - 
      name: Checkout code
      uses: actions/checkout@v3
    - 
      name: Compute short sha
      run:  |
        echo "SHORT_SHA=$(echo ${GITHUB_SHA} | cut -c1-8)" >> $GITHUB_ENV
    - 
      name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - 
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - 
      name: Build and Push Docker Images
      uses: docker/build-push-action@v3
      with:
        file: Dockerfile
        context: .
        push: true
        platforms: linux/amd64
        tags: |
          ${{ env.DOCKER_IMAGE_REPOSITORY }}:${{ github.ref_name }}-${{ env.SHORT_SHA }}
          ${{ env.DOCKER_IMAGE_REPOSITORY }}:${{ github.ref_name }}-latest
